steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - server/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: us-east4-docker.pkg.dev/mystical-app-490317-v0/alloynative/alloynative:latest
