apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alloynative
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/network-interfaces: >
          [{"network":"default","subnetwork":"default"}]
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      serviceAccountName: alloynative-run@mystical-app-490317-v0.iam.gserviceaccount.com
      containers:
        - image: us-east4-docker.pkg.dev/mystical-app-490317-v0/alloynative/alloynative:latest
          ports:
            - containerPort: 8080
          env:
            - name: ALLOYNATIVE_PROJECT_ID
              value: "mystical-app-490317-v0"
            - name: ALLOYNATIVE_REGION
              value: "us-east4"
            - name: ALLOYNATIVE_CLUSTER
              value: "mytest"
            - name: ALLOYNATIVE_INSTANCE
              value: "mytest-primary"
            - name: ALLOYNATIVE_DATABASE
              value: "my_application_db"
            - name: ALLOYNATIVE_DB_USER
              value: "alloynative-run@mystical-app-490317-v0.iam.gserviceaccount.com"
            - name: ALLOYNATIVE_EMBEDDING_MODEL
              value: "text-embedding-005"
            - name: ALLOYNATIVE_IP_TYPE
              value: "PRIVATE"
            - name: ALLOYNATIVE_RERANK_MODEL
              value: "gemini-2.0-flash-global"
            - name: ALLOYNATIVE_DEV_MODE
              value: "false"
