"""Fabricated Cymbal Shops demo against a live AlloyDB-backed AlloyNative index."""

from __future__ import annotations

import asyncio
import os

from alloynative import AlloyIndex


PRODUCTS_DDL = """
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10, 2),
    category VARCHAR(100),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding vector(768),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

INVENTORY_DDL = """
CREATE TABLE IF NOT EXISTS inventory (
    product_id BIGINT PRIMARY KEY,
    stock INTEGER NOT NULL,
    warehouse VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

PRODUCT_ROWS = [
    {
        "id": 101,
        "name": "Lightweight Running Shoe",
        "description": "Breathable daily trainer for road running",
        "category": "shoes",
        "price": 79.99,
        "metadata": {"brand": "demo", "color": "blue"},
    },
    {
        "id": 102,
        "name": "Trail Hiker Mid",
        "description": "Water-resistant boot for rugged weekend hikes",
        "category": "boots",
        "price": 129.00,
        "metadata": {"brand": "demo", "color": "brown"},
    },
]


async def main() -> None:
    index = await AlloyIndex.aconnect(
        table="products",
        project_id=os.environ["ALLOYNATIVE_PROJECT_ID"],
        region=os.environ["ALLOYNATIVE_REGION"],
        cluster=os.environ["ALLOYNATIVE_CLUSTER"],
        instance=os.environ["ALLOYNATIVE_INSTANCE"],
        database=os.environ["ALLOYNATIVE_DATABASE"],
        db_user=os.environ["ALLOYNATIVE_DB_USER"],
        ip_type=os.environ.get("ALLOYNATIVE_IP_TYPE", "PUBLIC"),
        text_columns=["name", "description"],
        metadata_column="metadata",
        embedding_column="embedding",
        embedding_source_column="description",
    )

    try:
        print("Capabilities:", index.capabilities)

        await index.client.execute(PRODUCTS_DDL)
        await index.client.execute(INVENTORY_DDL)

        await index.upsert(PRODUCT_ROWS)

        await index.client.execute(
            """
            INSERT INTO inventory (product_id, stock, warehouse)
            VALUES
                (:product_id_1, :stock_1, :warehouse_1),
                (:product_id_2, :stock_2, :warehouse_2)
            ON CONFLICT (product_id) DO UPDATE SET
                stock = EXCLUDED.stock,
                warehouse = EXCLUDED.warehouse,
                updated_at = NOW()
            """,
            {
                "product_id_1": 101,
                "stock_1": 5,
                "warehouse_1": "east",
                "product_id_2": 102,
                "stock_2": 0,
                "warehouse_2": "west",
            },
        )

        positive = await index.query(
            "comfortable running shoes",
            filters={"category": "shoes", "price__lte": 100},
            join_table="inventory",
            left_join_column="id",
            right_join_column="product_id",
            join_filter={"stock__gt": 0},
            limit=5,
        )

        print("Positive join result count:", len(positive.results))
        for item in positive.results:
            print(item)

        await index.client.execute(
            """
            UPDATE inventory
            SET stock = 0, updated_at = NOW()
            WHERE product_id = :product_id
            """,
            {"product_id": 101},
        )

        negative = await index.query(
            "comfortable running shoes",
            filters={"category": "shoes", "price__lte": 100},
            join_table="inventory",
            left_join_column="id",
            right_join_column="product_id",
            join_filter={"stock__gt": 0},
            limit=5,
        )

        print("Negative join result count:", len(negative.results))
        for item in negative.results:
            print(item)
    finally:
        await index.close()


asyncio.run(main())
